### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by yooksi** [yooksi/Odyssey#18]
We need to create a decent image that represents our project.

**Comment by Titus-Armillius** [comment]
![](https://i.imgur.com/cqCjEMF.png)

**Comment by yooksi** [comment]
I this it looks good, what do you think about adding a mosaic effect like this:

![odyssey_logo_mosaic_1](https://user-images.githubusercontent.com/16436920/81171343-84913380-8f9c-11ea-9cec-3dfc3358ec61.png)

*Note: Also slightly increased saturation.*

**Comment by Titus-Armillius** [comment]
Imo it makes the image too detailed, I suggest let's keep it as it is.

**Comment by Titus-Armillius** [comment]
Do you agree that this issue should be closed?
