### ISSUE TITLE
Longer day/night cycle

### ISSUE THREAD

**Issue by Titus-Armillius** [yooksi/Odyssey#22]
Changing the timeCycleSpeed to -60 does not affect the length of the day/night cycle.

This is based upon a timed test I did with the latest pre-release: v0.1

**Comment by yooksi** [comment]
Did you remember to restart the game after you changed the value in mod config?

**Comment by Titus-Armillius** [comment]
Yes;

**Comment by yooksi** [comment]
Do you have `MixinBootstrap` installed?

**Comment by Titus-Armillius** [comment]
Ok, no worries; seems to be working now. Dam, I can't believe I missed that.
