### ISSUE TITLE
Shorter day/night cycle

### ISSUE THREAD

**Issue by yooksi** [yooksi/Odyssey#4]
The day/night cycle should be 6 hours long, split into four 1<sup>1/2</sup> hour blocks.

**Comment by yooksi** [comment]
This feature has been tested and works with my API. I just need to sort the API documentation and publish it on CurseForge, then I will push the code and create our first release.

**Comment by yooksi** [comment]
Since I was having issues setting things up smoothly in the dev environment (even though I managed to get it working in the end) I decided to implement this feature without the API or library dependency that I originally planned to do. There was also fear that an external dependency might interfere with the mixin process and make it error-prone during MMD-Jam.

**Comment by Titus-Armillius** [comment]
This is fine. ^
